// scripts/lib/intel-merge.mjs — the ONE canonical way to serialize the word corpus.
// Reads verified staged cards, overlays them onto the committed rich corpus, and writes:
//   data/word-intel-rich.js   (build-only; full schema-v2 cards; read by gen-word-pages.mjs)
//   public/data/word-intel.js (slim; {def,fact,quote,author}; imported by the game at app.js)
// Sorted keys + stable field order => deterministic, byte-idempotent output.
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname } from "node:path";
import { pathToFileURL } from "node:url";

const FIELD_ORDER = [
  "word", "pos", "syllables", "letters", "ipa", "difficulty", "tags", "schemaVersion",
  "def", "senses", "etymology", "factsMeta", "facts", "quoteRef", "quote", "author",
  "mnemonic", "poem", "jokes", "lesson", "verified", "generatedAt",
];

const HEADER_RICH =
  "// data/word-intel-rich.js — BUILD-ONLY rich word corpus (schema v2).\n" +
  "// Read only by scripts/gen-word-pages.mjs; NOT imported by the game client.\n" +
  "// Generated by the wiki pipeline (scripts/lib/intel-merge.mjs); do not hand-edit.\n";

const HEADER_SLIM =
  "// public/data/word-intel.js — SLIM corpus the game imports (public/app.js).\n" +
  "// Per word: { def, gloss?, example?, ipa?, pos?, fact?, quote?, author? }. Rich page corpus: data/word-intel-rich.js.\n" +
  "// Generated by scripts/lib/intel-merge.mjs; do not hand-edit.\n";

const WORDINTEL_FOOTER =
  'export function wordIntel(word) {\n' +
  '  return WORD_INTEL[String(word || "").toUpperCase()] || null;\n' +
  '}\n';

function orderCard(card) {
  const out = {};
  for (const k of FIELD_ORDER) if (card[k] !== undefined) out[k] = card[k];
  for (const k of Object.keys(card)) if (!(k in out)) out[k] = card[k];
  return out;
}

function slimCard(card) {
  const out = { def: card.def };
  const sense = Array.isArray(card.senses) ? card.senses[0] : null;
  if (sense?.gloss) out.gloss = sense.gloss;       // short definition for the celebration headword
  if (sense?.example) out.example = sense.example; // vivid sentence using the word
  if (card.ipa) out.ipa = card.ipa;                // headword line: /ˈfoʊ.kəl/
  if (card.pos) out.pos = card.pos;                // · adjective
  const fact = (Array.isArray(card.facts) && card.facts[0]) || card.fact;
  if (fact) out.fact = fact;
  if (card.quote) out.quote = card.quote;
  if (card.author) out.author = card.author;
  return out;
}

function sortedMap(cards, shape) {
  const out = {};
  for (const k of Object.keys(cards).sort()) out[k] = shape(cards[k]);
  return out;
}

/** Read all *.verified.json in a staging dir into { WORD: card } (UPPERCASE keys). Skips non-verified + unparseable. */
export function readVerifiedCards(stagingDir) {
  const map = {};
  if (!existsSync(stagingDir)) return map;
  for (const f of readdirSync(stagingDir)) {
    if (!f.endsWith(".verified.json")) continue;
    const slug = f.slice(0, -".verified.json".length);
    try {
      const card = JSON.parse(readFileSync(`${stagingDir}/${f}`, "utf8"));
      if (card && card.def) map[slug.toUpperCase()] = card;
    } catch { /* skip unparseable */ }
  }
  return map;
}

export function writeRich(richPath, cards) {
  mkdirSync(dirname(richPath), { recursive: true });
  const map = sortedMap(cards, orderCard);
  writeFileSync(richPath, `${HEADER_RICH}export const WORD_INTEL = ${JSON.stringify(map, null, 2)};\n`);
  return Object.keys(map).length;
}

export function writeSlim(slimPath, cards) {
  mkdirSync(dirname(slimPath), { recursive: true });
  const map = sortedMap(cards, slimCard);
  writeFileSync(slimPath, `${HEADER_SLIM}export const WORD_INTEL = ${JSON.stringify(map, null, 2)};\n\n${WORDINTEL_FOOTER}`);
  return Object.keys(map).length;
}

/** Overlay verified staging onto the committed rich corpus, then write both files. Returns { merged, added, keys }. */
export async function mergeStagingToCorpus({ stagingDir, richPath, slimPath }) {
  const existing = existsSync(richPath) ? { ...(await import(pathToFileURL(richPath).href)).WORD_INTEL } : {};
  const staged = readVerifiedCards(stagingDir);
  const cards = { ...existing, ...staged }; // staged overlays existing
  writeRich(richPath, cards);
  writeSlim(slimPath, cards);
  return { merged: Object.keys(cards).length, added: Object.keys(staged).length, keys: Object.keys(cards) };
}

// CLI: `node scripts/lib/intel-merge.mjs` re-serializes the committed corpus with the current
// slim/rich projections (empty staging = no content change, just a wider slim shape). Idempotent.
import { fileURLToPath } from "node:url";
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const ROOT = new URL("../../", import.meta.url).pathname;
  const res = await mergeStagingToCorpus({
    stagingDir: ROOT + ".intel-staging-empty", // does not exist → readVerifiedCards returns {}
    richPath: ROOT + "data/word-intel-rich.js",
    slimPath: ROOT + "public/data/word-intel.js",
  });
  console.log(`reslim: ${res.keys.length} words → public/data/word-intel.js`);
}
